# Generated by Django 6.0.7 on 2026-07-19 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp', models.CharField(choices=[('NONE', 'Brak przynależności'), ('SWAMP_CAMP', 'Obóz na bagnie'), ('OLD_CAMP', 'Stary Obóz'), ('NEW_CAMP', 'Nowy Obóz')], default='NONE', max_length=20)),
                ('level', models.IntegerField(default=0)),
                ('guild', models.CharField(default='NONE', max_length=20)),
                ('experience', models.IntegerField(default=0)),
                ('skill_points', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('mana', models.IntegerField(default=10)),
                ('life', models.IntegerField(default=50)),
                ('weapon_prot', models.IntegerField(default=0)),
                ('arrow_prot', models.IntegerField(default=0)),
                ('fire_prot', models.IntegerField(default=0)),
                ('magic_prot', models.IntegerField(default=0)),
                ('onehand_skill', models.IntegerField(default=0)),
                ('twohand_skill', models.IntegerField(default=0)),
                ('bow_skill', models.IntegerField(default=0)),
                ('crossbow_skill', models.IntegerField(default=0)),
                ('lockpick_skill', models.IntegerField(default=0)),
                ('pickpock_skill', models.IntegerField(default=0)),
                ('magic_skill', models.IntegerField(default=0)),
                ('sneaking', models.BooleanField(default=False)),
                ('acrobatics', models.BooleanField(default=False)),
                ('ore_balance', models.IntegerField(default=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
