# Generated by Django 6.0.7 on 2026-07-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='action_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='current_energy',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='max_energy',
            field=models.IntegerField(default=100),
        ),
    ]
