# Generated by Django 6.0.7 on 2026-07-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_playerprofile_action_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBluePrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('damage', models.IntegerField(default=0)),
                ('required_strength', models.IntegerField(default=0)),
                ('base_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_market_listed', models.BooleanField(default=False)),
                ('market_price', models.IntegerField(blank=True, null=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.itemblueprint')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='characters.playerprofile')),
            ],
        ),
    ]
