# Generated by Django 6.0.7 on 2026-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_itemblueprint_owneditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneditem',
            name='is_equipped',
            field=models.BooleanField(default=False),
        ),
    ]
